import os
from collections import defaultdict
from typing import Any, List, Optional

from opentelemetry import trace
from pydantic_ai import Tool

DEFAULT_IGNORED_DIRS = [
    ".git",        # Git version control
    ".venv",       # Python virtual environments
    "assets",      # Static assets (often frontend assets)
    ".idea",       # JetBrains IDE configuration
    "k8s",         # Kubernetes configurations
    "logs",        # Log files
    ".logs",       # Log files (alternative)
    "__pycache__", # Python cache files
    ".old-venv",   # Old Python virtual environments
    "node_modules", # Node.js dependencies
    "dist",        # Distribution folder (build output)
    "build",       # Build folder (build output)
    "cache",       # Cache directories (can be large)
    ".next",       # Next.js build folder
    "out",         # Next.js static export
    "coverage",    # Test coverage reports
    ".nuxt",       # Nuxt.js build folder
    ".output",     # Nuxt 3 build folder
    "public/build", # Static files generated by frontend frameworks
    "static",      # Static files directory
    "uploads",     # File uploads (often in backend apps)
    "storage",     # Backend storage (e.g., Laravel or similar)
    "tmp",         # Temporary files
    "temp",        # Temporary files
    ".DS_Store",   # macOS system file
    "Thumbs.db",   # Windows system file
]

DEFAULT_IGNORED_EXTENSIONS = [
    ".pyc",            # Python bytecode files (generated during Python execution)
    ".class",          # Java class files (compiled from Java source code)
    ".o",              # Object files (compiled from source code)
    ".so",             # Shared libraries (compiled, platform-specific)
    ".dll",            # Dynamic Link Library files (Windows platform-specific compiled files)
    ".exe",            # Executable files (platform-specific)
    ".jar",            # Java archive files (containing compiled Java code)
    ".war",            # Web archive files (Java-based web apps)
    ".ear",            # Enterprise archive files (Java enterprise applications)
    ".zip",            # ZIP archive files (compressed collections of files)
    ".tar.gz",         # Compressed TAR archive files (using gzip compression)
    ".tgz",            # Gzipped TAR archive files (alternative to .tar.gz)
    ".rar",            # RAR archive files (compressed file format)
    ".log",            # Log files (can grow very large, not useful for analysis)
    ".tmp",            # Temporary files (generated during processing or build)
    ".temp",           # Temporary files (same as .tmp, used for intermediate processing)
    ".swp",            # Swap files (generated by editors like Vim for crash recovery)
    ".iml",            # IntelliJ IDEA project files (IDE-specific, not relevant to source code)
    ".cache",          # Cache files (usually generated during build or runtime, not needed)
    ".dat",            # Generic data files (often binary or non-text, not typically used in analysis)
    ".db",             # Database files (local DB storage, often irrelevant)
    ".sqlite",         # SQLite database files (small embedded DB, often shouldn't be analyzed)
    ".sqlite3",        # SQLite 3 database files (same as .sqlite, used for embedded databases)
    
    # Environment files (contain sensitive or configuration data):
    ".env",            # Main environment variable file (contains sensitive keys, settings)
    ".env.local",      # Local environment variables (for local development, shouldn't be shared)
    ".env.development",# Development-specific environment variables (contains dev-specific settings)
    ".env.production", # Production-specific environment variables (contains live API keys, DB credentials)
    ".env.test",       # Test-specific environment variables (used for testing environments)
    ".env.example",    # Example environment file (used for sharing configurations without sensitive data)
    
    # Lock and PID files (used by processes to track running instances or prevent duplication):
    ".lock",           # Lock files (used to signal that a process is running and to prevent multiple instances)
    ".pid",            # PID files (store process IDs, used for managing background processes)
    ".pid.lock",       # Lock file associated with PID files (same purpose as .pid but for locking)
    ".pidfile",        # PID files (alternative naming, still contains process IDs)
    ".pid.lockfile",   # Lock file for PID files (same as .pid.lock)
    ".pidfile.lock",   # Another variation of PID lock file naming
    ".pidfile.lockfile", # Yet another variation of PID lock file naming
]



class ListFilesTool:
    def __init__(
        self,
        ignored_dirs: Optional[List[str]] = DEFAULT_IGNORED_DIRS,
        ignored_extensions: Optional[List[str]] = DEFAULT_IGNORED_EXTENSIONS,
    ):
        self.ignored_dirs = ignored_dirs or []
        self.ignored_extensions = ignored_extensions or []

    def get_tool(self):
        return Tool(self._run, name="List-Files-Tool", takes_ctx=False, max_retries=2)

    def _run(self, directory: str) -> Any:
        """List files in a directory recursively, grouping them by directory.

        This function walks through the directory tree starting from the given path,
        collecting all files and organizing them by their parent directories.
        It skips any directories specified in the ignored_dirs list.

        Args:
            directory (str): The path to the directory to list files from.

        Returns:
            str: A formatted string containing the directory structure and files,
                with files grouped by their parent directories. Each directory's
                files are listed on a new line, sorted alphabetically.

        Example:
            Files grouped by directory (relative to /path/to/dir):
            /: ['file1.txt', 'file2.txt']
            /subdir: ['file3.txt', 'file4.txt']
        """
        trace.get_current_span().set_attribute("input", directory)
        directory = directory
        if directory[-1] == "/":
            directory = directory[:-1]

        # Group files by directory
        dir_files = defaultdict(list)

        for root, dirs, files in os.walk(directory):
            # Skip ignored directories
            if self.ignored_dirs and any(ignored_dir in root for ignored_dir in self.ignored_dirs):
                continue

            # Get relative directory path
            rel_dir = os.path.relpath(root, directory)
            if rel_dir == ".":
                rel_dir = "/"
            else:
                rel_dir = "/" + rel_dir

            # Add files to this directory
            for filename in files:
                # Skip files with ignored extensions
                if self.ignored_extensions and any(filename.endswith(ext) for ext in self.ignored_extensions):
                    continue
                dir_files[rel_dir].append(filename)

        # Sort directories and files for readability
        result = f"Files grouped by directory (relative to {directory}):\n"

        for dir_path in sorted(dir_files.keys()):
            files = sorted(dir_files[dir_path])
            result += f"\n{dir_path}: {files}\n"

        if not dir_files:
            result = f"No files found in {directory}."

        trace.get_current_span().set_attribute("output", result)
        return result
